version: '3.3'

services:
  kong:
    image: kong/kong-gateway:3.8.0.0
    volumes:
      - "./config:/usr/local/kong/declarative"
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:7002
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    ports:
      - "127.0.0.1:8005:8000/tcp" # Proxy
      - "127.0.0.1:7990:8001/tcp" # Admin
      - "127.0.0.1:7002:8002"     # GUI
      - "127.0.0.1:8443:8443/tcp" # GUI
      - "127.0.0.1:8444:8444/tcp" # Admin (SSL)