_format_version: "2.1"
services:
  - name: auth-service
    url: http://172.19.0.4:9898
    routes:
      - name: sign-up
        paths:
          - /auth/v1/signup
  - name: user-service
    url: http://172.19.0.5:9899
    routes:
      - name: get-user
        paths:
          - /user/v1/getUser